// Generated by CoffeeScript 1.8.0

/*
This is arguments method decorator checkers
 */

(function() {
  var _;

  _ = require('lodash');

  module.exports = {
    rejectOnInvalidFilenameType: function(methodBody) {
      return function(filename, cb) {
        if (!_.isString(filename)) {
          return cb(TypeError("must be called with filename as String, but got:\n|filename| = |" + filename + "|"));
        }
        return methodBody.call(this, filename, cb);
      };
    }
  };

}).call(this);
