// Generated by CoffeeScript 1.6.1

/*
This class compile and load files
*/


(function() {
  var CoffeeScript, Eco, FileProcessor, Jade, XXHash, fs, path, rejectOnInvalidFilenameType, _;

  fs = require('fs');

  path = require('path');

  _ = require('lodash');

  XXHash = require('xxhash');

  CoffeeScript = require('coffee-script');

  Eco = require('eco');

  Jade = require('jade');

  /*
  Checker method decorator
  */


  rejectOnInvalidFilenameType = function(methodBody) {
    return function(filename, cb) {
      if (!_.isString(filename)) {
        return cb(TypeError("must be called with filename as String, but got:\n|filename| = |" + filename + "|"));
      }
      return methodBody.call(this, filename, cb);
    };
  };

  FileProcessor = (function() {
    var CS_BARE, HASH_SALT;

    HASH_SALT = 0xCAFEBABE;

    CS_BARE = true;

    function FileProcessor(_options_) {
      this._options_ = _options_ != null ? _options_ : {};
      this._compilers_ = this._getAsyncCompilers(this._getJadeSettings(this._options_.jade));
      _.assign(this._compilers_, this._options_.third_party_compilers);
    }

    /*
    This method load one file and, if it needed, compile it
    */


    FileProcessor.prototype.loadFile = rejectOnInvalidFilenameType(function(filename, cb) {
      var file_ext,
        _this = this;
      file_ext = path.extname(filename);
      if (this._compilers_[file_ext] != null) {
        return fs.readFile(filename, 'utf8', function(err, data) {
          if (err) {
            return cb(err);
          }
          return _this._compilers_[file_ext](_this._stripBOM(data), filename, function(err, result, must_be_parsed) {
            var res;
            if (err) {
              return cb(err);
            }
            res = ("\n// " + filename + " \n") + result;
            return cb(null, res, must_be_parsed);
          });
        });
      } else {
        return cb(null, false);
      }
    });

    /*
    This method generate digest for file content
    */


    FileProcessor.prototype.getFileDigest = rejectOnInvalidFilenameType(function(filename, cb) {
      var hasher, stream;
      hasher = new XXHash(HASH_SALT);
      stream = fs.createReadStream(filename);
      stream.on('data', function(data) {
        return hasher.update(data);
      });
      stream.on('error', function(err) {
        return cb(err);
      });
      return stream.on('end', function() {
        return cb(null, hasher.digest());
      });
    });

    /*
    This method return supported extentions
    */


    FileProcessor.prototype.getSupportedFileExtentions = function() {
      return _.keys(this._compilers_);
    };

    /*
    This method from node.js lib/module
    // Remove byte order marker. This catches EF BB BF (the UTF-8 BOM)
    // because the buffer-to-string conversion in `fs.readFileSync()`
    // translates it to FEFF, the UTF-16 BOM.
    */


    FileProcessor.prototype._stripBOM = function(content) {
      if (content.charCodeAt(0) === 0xFEFF) {
        return content.slice(1);
      } else {
        return content;
      }
    };

    /*
    This internal method for Jade settings
    */


    FileProcessor.prototype._getJadeSettings = function(options) {
      if (options == null) {
        options = {};
      }
      return _.defaults({
        client: true
      }, options, {
        pretty: true,
        self: true,
        compileDebug: false
      });
    };

    /*
    This is Async compilers list.
    @return - error, data, isRealCode (ie. may have 'require' and should to be processed)
    */


    FileProcessor.prototype._getAsyncCompilers = function(jade_settings) {
      return {
        '.js': function(data, filename, cb) {
          return cb(null, data, true);
        },
        '.json': function(data, filename, cb) {
          return cb(null, "module.exports = " + data);
        },
        '.coffee': function(data, filename, cb) {
          var content;
          content = CoffeeScript.compile(data, {
            bare: CS_BARE
          });
          return cb(null, content, true);
        },
        '.eco': function(data, filename, cb) {
          var content;
          content = Eco.precompile(data);
          return cb(null, "module.exports = " + content);
        },
        '.jade': function(data, filename, cb) {
          var content;
          content = Jade.compile(data, _.assign(jade_settings, {
            filename: filename
          }));
          return cb(null, "module.exports = " + content);
        }
      };
    };

    return FileProcessor;

  })();

  module.exports = FileProcessor;

}).call(this);
