// Generated by CoffeeScript 1.6.1

/*
This class build whole codebase for path

Короче, здесь у нас модуль, который получает на вход 
путь и возвращает полный комплект из путей (для разрешения require)
и скомпилированное содерживое файлов

Над форматом  сильно много думать, думаеццо надо в комплекте с ресолвингом
решать, как будет удобнее, так что пока формат ПЛАВАЮЩИЙ!!! 
Был предупрежден? Свободен!
*/


(function() {
  var AsyncCache, Gatherer, LRU, Resolver, async, detective, fs, path, util, _,
    _this = this,
    __slice = [].slice;

  fs = require('fs');

  path = require('path');

  _ = require('lodash');

  async = require('async');

  detective = require('detective');

  AsyncCache = require('async-cache');

  LRU = require('lru-cache');

  util = require('util');

  Resolver = require('async-resolve');

  Gatherer = (function() {
    var MAX_AGE;

    MAX_AGE = 1000 * 60 * 60 * 10;

    function Gatherer(_file_processor_, _options_) {
      var _ref,
        _this = this;
      this._file_processor_ = _file_processor_;
      this._options_ = _options_ != null ? _options_ : {};
      this._dependenciesTreeSaver = function(_arg) {
        var pack_cache, parent, path_name, real_file_name;
        path_name = _arg.path_name, parent = _arg.parent, real_file_name = _arg.real_file_name, pack_cache = _arg.pack_cache;
        return Gatherer.prototype._dependenciesTreeSaver.apply(_this, arguments);
      };
      this._findRequiresAndAddToQueue = function(_arg) {
        var data, may_have_reqire, pack_cache, path_name, real_file_name;
        may_have_reqire = _arg.may_have_reqire, data = _arg.data, real_file_name = _arg.real_file_name, path_name = _arg.path_name, pack_cache = _arg.pack_cache;
        return Gatherer.prototype._findRequiresAndAddToQueue.apply(_this, arguments);
      };
      this._queueFn = function(_arg, queue_cb) {
        var pack_cache, parent, path_name;
        path_name = _arg.path_name, parent = _arg.parent, pack_cache = _arg.pack_cache;
        return Gatherer.prototype._queueFn.apply(_this, arguments);
      };
      this._pathfinder_ = new Resolver();
      (_ref = this._pathfinder_).addExtensions.apply(_ref, this._file_processor_.getSupportedFileExtentions());
      this._loader_cache_ = this._buildLoaderCache();
      this._require_cache_ = LRU({
        max: 1000,
        maxAge: MAX_AGE
      });
    }

    /*
    This method reset all caches
    */


    Gatherer.prototype.resetCaches = function() {
      this._loader_cache_.reset();
      this._require_cache_.reset();
      return null;
    };

    /*
    This is Async version of packer
    */


    Gatherer.prototype.buildModulePack = function(path_name, options, main_cb) {
      var load_queue, pack_cache,
        _this = this;
      if (options == null) {
        options = {};
      }
      pack_cache = {
        dependencies_tree: {},
        names_map: {},
        source_code: {},
        err: null,
        filters: [],
        requireless: []
      };
      if (options.filters != null) {
        pack_cache.filters = this._forceFilterToArray(options.filters);
      }
      if (options.requireless != null) {
        pack_cache.requireless = this._forceFilterToArray(options.requireless);
      }
      pack_cache.queue_obj = load_queue = async.queue(this._queueFn, 50);
      load_queue.drain = function() {
        if (!pack_cache.err) {
          return main_cb(null, {
            dependencies_tree: pack_cache.dependencies_tree,
            names_map: pack_cache.names_map,
            source_code: pack_cache.source_code
          });
        } else {
          return main_cb(pack_cache.err);
        }
      };
      return load_queue.push({
        path_name: path_name,
        parent: '.',
        pack_cache: pack_cache
      }, function(err) {
        return pack_cache.err = err;
      });
    };

    /*
    Oh!
    Many things here, but its price of async code
    */


    Gatherer.prototype._queueFn = function(_arg, queue_cb) {
      var pack_cache, parent, path_name,
        _this = this;
      path_name = _arg.path_name, parent = _arg.parent, pack_cache = _arg.pack_cache;
      return async.waterfall([
        function(waterfall_cb) {
          return _this._pathfinder_.resolveAbsolutePath(path_name, path.dirname(parent), waterfall_cb);
        }, function(real_file_name, waterfall_cb) {
          if (!_this._dependenciesTreeSaver({
            path_name: path_name,
            parent: parent,
            real_file_name: real_file_name,
            pack_cache: pack_cache
          })) {
            return queue_cb();
          }
          return _this._getFromCacheWithValidation(real_file_name, function(err, data) {
            if (err) {
              return waterfall_cb(err);
            }
            return waterfall_cb(null, data.digest, data.content, {
              path_name: path_name,
              real_file_name: real_file_name
            });
          });
        }, function(digest, content, _arg1, waterfall_cb) {
          var data, may_have_reqire, path_name, real_file_name;
          real_file_name = _arg1.real_file_name, path_name = _arg1.path_name;
          data = content[0], may_have_reqire = content[1];
          _this._fileDataSaver({
            digest: digest,
            data: data,
            real_file_name: real_file_name,
            pack_cache: pack_cache
          });
          _this._findRequiresAndAddToQueue({
            may_have_reqire: may_have_reqire,
            data: data,
            real_file_name: real_file_name,
            path_name: path_name,
            pack_cache: pack_cache
          });
          return waterfall_cb();
        }
      ], function(err) {
        return queue_cb(err);
      });
    };

    /*
    This internal method for loaders cache, to slow get it from disk
    YES, it will be needed to implement cache invalidator :(
    */


    Gatherer.prototype._buildLoaderCache = function() {
      var _this = this;
      return new AsyncCache({
        max: 100,
        maxAge: MAX_AGE,
        load: function(key, cb) {
          return _this._getFileDataAndMeta(key, cb);
        }
      });
    };

    /*
    This is converter for ensure filter is Array
    @arg may be one value or Array
    */


    Gatherer.prototype._forceFilterToArray = function() {
      var filters_list, first_filter, other_filters;
      first_filter = arguments[0], other_filters = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      return filters_list = !_.isArray(first_filter) ? [first_filter].concat(other_filters) : first_filter;
    };

    /*
    This method get data and meta from cache with cache validation
    At now try to use re-calculated file hash
    */


    Gatherer.prototype._getFromCacheWithValidation = function(real_file_name, meth_cb) {
      var _this = this;
      return async.parallel({
        current_digest: function(parallel_cb) {
          return _this._file_processor_.getFileDigest(real_file_name, parallel_cb);
        },
        all_data: function(parallel_cb) {
          return _this._loader_cache_.get(real_file_name, parallel_cb);
        }
      }, function(err, data) {
        if (err) {
          return meth_cb(err);
        }
        if (data.current_digest === data.all_data.digest) {
          return meth_cb(null, data.all_data);
        } else {
          _this.resetCaches();
          return _this._loader_cache_.get(real_file_name, meth_cb);
        }
      });
    };

    /*
    This method searching for requires, its just stub.
    later I re-write it to class
    to substitute detective with my own logic and acorn
    */


    Gatherer.prototype._findRequiresItself = function(data) {
      return detective(data);
    };

    /*
    This method find requires in files, if they need it and 
    add to queue new files for recurse working
    */


    Gatherer.prototype._findRequiresAndAddToQueue = function(_arg) {
      var child, childrens, data, may_have_reqire, pack_cache, path_name, real_file_name, res, _i, _len;
      may_have_reqire = _arg.may_have_reqire, data = _arg.data, real_file_name = _arg.real_file_name, path_name = _arg.path_name, pack_cache = _arg.pack_cache;
      if (may_have_reqire === true && this._isFilesMustBeProcessed(pack_cache.requireless, path_name)) {
        childrens = !this._require_cache_.has(real_file_name) ? (res = this._findRequiresItself(data), this._require_cache_.set(real_file_name, res), res) : this._require_cache_.get(real_file_name);
        for (_i = 0, _len = childrens.length; _i < _len; _i++) {
          child = childrens[_i];
          pack_cache.queue_obj.push({
            path_name: child,
            parent: real_file_name,
            pack_cache: pack_cache
          }, function(err) {
            return pack_cache.err = err;
          });
          null;
        }
      }
      return null;
    };

    /*
    This method get content and meta for filename
    */


    Gatherer.prototype._getFileDataAndMeta = function(real_file_name, step_cb) {
      var _this = this;
      return async.parallel({
        digest: function(parallel_cb) {
          return _this._file_processor_.getFileDigest(real_file_name, parallel_cb);
        },
        content: function(parallel_cb) {
          return _this._file_processor_.loadFile(real_file_name, parallel_cb);
        }
      }, step_cb);
    };

    /*
    This part-method handle save to tree
    if file exists or unnided - return false
    */


    Gatherer.prototype._dependenciesTreeSaver = function(_arg) {
      var dep_tree_par, pack_cache, parent, path_name, real_file_name, _base, _ref;
      path_name = _arg.path_name, parent = _arg.parent, real_file_name = _arg.real_file_name, pack_cache = _arg.pack_cache;
      dep_tree_par = (_ref = (_base = pack_cache.dependencies_tree)[parent]) != null ? _ref : _base[parent] = {};
      if (dep_tree_par[path_name] != null) {
        return false;
      }
      if (!this._isFilesMustBeProcessed(pack_cache.filters, path_name)) {
        dep_tree_par[path_name] = null;
        return false;
      }
      if (this._pathfinder_.isCoreModule(real_file_name)) {
        dep_tree_par[path_name] = null;
        return false;
      }
      dep_tree_par[path_name] = real_file_name;
      return true;
    };

    /*
    This method save data
    void return
    */


    Gatherer.prototype._fileDataSaver = function(_arg) {
      var data, digest, pack_cache, real_file_name, _base, _ref;
      digest = _arg.digest, data = _arg.data, real_file_name = _arg.real_file_name, pack_cache = _arg.pack_cache;
      pack_cache.names_map[real_file_name] = digest;
      if ((_ref = (_base = pack_cache.source_code)[real_file_name]) == null) {
        _base[real_file_name] = data;
      }
      return null;
    };

    /*
    This is proceed filter
    return 'true' if file MUST be processed, 
    ie it filename NOT in list - it will be processed
    */


    Gatherer.prototype._isFilesMustBeProcessed = function(filters_list, path_name) {
      return !_.any(filters_list, function(filter) {
        return filter === path_name;
      });
    };

    return Gatherer;

  })();

  module.exports = Gatherer;

}).call(this);
